{

  "msg": "Licensed options SID=ORCLCDB: []",

  "_ansible_verbose_always": true,

  "_ansible_no_log": null,

  "changed": false,

  "item": {

    "sid": "ORCLCDB",

    "options": []

  },

  "ansible_loop_var": "item",

  "_ansible_item_label": "ORCLCDB"

}
 
{

  "msg": "Licensed options SID=SAMTST1: []",

  "_ansible_verbose_always": true,

  "_ansible_no_log": null,

  "changed": false,

  "item": {

    "sid": "SAMTST1",

    "options": []

  },

  "ansible_loop_var": "item",

  "_ansible_item_label": "SAMTST1"

}
 
{

  "msg": "Licensed options SID=SAMTST2: []",

  "_ansible_verbose_always": true,

  "_ansible_no_log": null,

  "changed": false,

  "item": {

    "sid": "SAMTST2",

    "options": []

  },

  "ansible_loop_var": "item",

  "_ansible_item_label": "SAMTST2"

}
 
